### ISSUE TITLE
Bestaat deze delete button nog?

### ISSUE THREAD

**Issue by jasperdj** [ron-from-nl/FinalCrypt#2]
https://github.com/ron-from-nl/FinalCrypt/blob/daad18e1d3686e55ffbbf40f49d6192e6fa242d1/src/rdj/GUIFX.java#L397

**Comment by ron-from-nl** [comment]
Haha retro hè? De Swing JButton zit nog gewoon in JSE8. Ik heb in FinalCrypt gebruikt door deze toe te voegen aan de JFileChooser (die heeft geen delete knop en functie). Ik heb besloten om (op termijn) zelf een 3D filemanager te ontwikkelen, dan krijgt FinalCrypt een hele moderne 3D (game achtige) geanimeerde interface. Wel veel werk, aangezien alle benodigde windows widgets vanaf de grond af ontwikkeld moeten worden, los van hoeveel werk het is om een 3D filemanager te ontwikkelen, wat natuurlijk de meest gecompliceerde 3D widget zal zijn. Omdat dit zo'n grote opdracht is, wil ik eerst weten of het de moeite loont, om met Java door te gaan, aangezien de toekomst voor Java erg onzeker is momenteel.
