### ISSUE TITLE
Windows portable version

### ISSUE THREAD

**Issue by copart** [ron-from-nl/FinalCrypt#3]
Question... What are the chances that a portable version for windows could some day exist? If not portable, user-installable without admin rights.

Thank you for your release!

**Comment by Eyremba** [comment]
Isn't the JAR file "portable"? (FinalCrypt_Z.jar)

**Comment by ron-from-nl** [comment]
Download and install [JPortable64](https://portableapps.com/downloading/?a=Java64&n=jPortable64&s=s&p=&d=pa&f=jPortable64_8_Update_181_online.paf.exe) (a portable version of a JRE/JVM) on a USB stick and copy [FinalCrypt_Z.jar](https://github.com/ron-from-nl/FinalCrypt/releases/download/latest/FinalCrypt_Z.jar) on the USB stick in the dir:
[JPortable Install Dir]\CommonFiles\Java64\App

Execute as follows (from: cmd / bash):
GUI: bin\java.exe -jar App\FinalCrypt_Z.jar
CLI: bin\java.exe -cp App\FinalCrypt_Z.jar rdj.CLUI --help

Just tested successfully

Of course on Windows you can also start the GUI from a "FinalCrypt.bat" batch file.
Create a new txt file called "FinalCrypt.bat" and add the following line (example)
==============================================================
"C:\Users\Ron de Jong\Downloads\CommonFiles\Java64\bin\java.exe" -jar "C:\Users\Ron de Jong\Downloads\CommonFiles\Java64\App\FinalCrypt_Z.jar"
==============================================================
Just correct the paths to your location (I installed and tested in my Downloads directory)

**Comment by copart** [comment]
thank you!

**Comment by ron-from-nl** [comment]
> thank you!

you're welcome

[the website](https://sites.google.com/site/ronuitholland/home/finalcrypt) now also has a little link called: [Run FinalCrypt Portable](https://raw.githubusercontent.com/ron-from-nl/FinalCrypt/master/RunPortable.txt)
