### ISSUE TITLE
garbled chinese character

### ISSUE THREAD

**Issue by sunnos** [ron-from-nl/FinalCrypt#4]
ubuntu18.04 
install finalcrypt_linux_x86_64_debian_based.deb
There is a Chinese garbled character

![2019-11-2710:06:15](https://user-images.githubusercontent.com/26592074/69687803-27e14100-10ff-11ea-92a1-8e088ef4eb5f.png)

**Comment by ron-from-nl** [comment]
Thank you for reporting and indeed you are right.
The FileChooser panels are incorrectly displaying the non-latin UTF chars.
Selecting and en/decrypting these files works correctly check the log tab (upper left).
I'll look into it right away. Thank you and I'll respond ASAP

Ron

**Comment by ron-from-nl** [comment]
I found the cause, I will update within 24 hours. Keep an eye out for version 5.6.7

**Comment by sunnos** [comment]
thanks!!! Just wonderful
----- 原始邮件 -----
发件人：Ron de Jong <notifications@github.com>
收件人：ron-from-nl/FinalCrypt <FinalCrypt@noreply.github.com>
抄送人：sunnos <sunnos@sina.com>,  Author <author@noreply.github.com>
主题：Re: [ron-from-nl/FinalCrypt] garbled chinese character (#4)
日期：2019年11月27日 11点42分

I found the cause, I will update within 24 hours. Keep an eye out for version 5.6.7

**Comment by ron-from-nl** [comment]
Your welcome Sunnos just finished releasing FinalCrypt 5.6.7
Thank you for reporting the issue and for using FinalCrypt

Regards,
Ron de Jong
